version: "3"
services:
  mysqldb:
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: trailspwd
      MYSQL_DATABASE: speedway_trails_db
  trivia-api:
    build: .
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: trailspwd
      DB_NAME: speedway_trails_db
    depends_on:
      - mysqldb
    ports:
      - "8200:8080"
volumes:
  mysql_volume: {}